### ISSUE TITLE
ValueError in IEEE parsing

### ISSUE THREAD

**Issue by ctalkington** [ctalkington/python-ipp#5]
```
2020-04-02 11:06:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 123, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 163, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 50, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 92, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 130, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/ipp/config_flow.py", line 63, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/usr/src/homeassistant/homeassistant/components/ipp/config_flow.py", line 40, in validate_input
    printer = await ipp.printer()
  File "/usr/local/lib/python3.7/site-packages/pyipp/ipp.py", line 211, in printer
    return Printer.from_dict(data)
  File "/usr/local/lib/python3.7/site-packages/pyipp/models.py", line 119, in from_dict
    info=Info.from_dict(data), markers=markers, state=State.from_dict(data)
  File "/usr/local/lib/python3.7/site-packages/pyipp/models.py", line 32, in from_dict
    parsed_device_id = parse_ieee1284_device_id(device_id)
  File "/usr/local/lib/python3.7/site-packages/pyipp/parser.py", line 12, in parse_ieee1284_device_id
    cast(Tuple[str, str], x.split(":", 2)) for x in device_id.split(";")
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**Comment by ctalkington** [comment]
closed by #6
