### ISSUE TITLE
OKI printers not working

### ISSUE THREAD

**Issue by LorbusChris** [ctalkington/python-ipp#515]
I have an OKI C822 printer which has HomeAssistant reporting:
```
IPP version not supported by the printer
```
This issue was originally filed by @iagosansouza here: https://github.com/home-assistant/core/issues/93211

Per @ctalkington suggestion in https://github.com/home-assistant/core/issues/93211#issuecomment-1687409628, I'm opening this issue to provide the output of `python debug.py` in the hope that it'll help fix the issue.

The printer is configured to use `ipp` instead of `ipps`, so I changed the URL in the `debug.py` script accordingly.

Interestingly, trying  URL `ipp://192.168.1.73:631/ipp/print` yields a 404:
```
⬢[lorbus@toolbox examples]$ python debug.py 
/var/home/lorbus/code/python-ipp/examples/debug.py:50: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "/var/home/lorbus/code/python-ipp/examples/debug.py", line 51, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/var/home/lorbus/code/python-ipp/examples/debug.py", line 12, in main
    response = await ipp.raw(
               ^^^^^^^^^^^^^^
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/pyipp/ipp.py", line 208, in raw
    return await self._request(data=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/pyipp/ipp.py", line 142, in _request
    raise IPPResponseError(
pyipp.exceptions.IPPResponseError: ('HTTP 404', {'content-type': 'text/html', 'message': '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">\n<HTML>\n\n<HEAD>\n\t<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">\n<title>HTTP 404</title>\n</HEAD>\n\n<BODY BGCOLOR="#FFFFFF">\n\n<P>\n<TABLE BORDER="0"  CELLPADDING="4" WIDTH="560">\n\t<TR>\n\t\t<TD HEIGHT="50" VALIGN="BOTTOM" NOWRAP><font face="Arial" size="6">Not Found</font></TD>\n\t</TR>\n</TABLE>\n</P>\n\n<BLOCKQUOTE>\n<TABLE BORDER="0" WIDTH="560">\n\t<TR>\n\t\t<TD WIDTH="100%"><font face="Arial">HTTP-1.0 / 404</font></TD>\n\t</TR>\n</TABLE>\n</BLOCKQUOTE>\n\n</BODY>\n</HTML>\n', 'status-code': 404})
```

Removing `/print` from the URL (now `ipp://192.168.1.73:631/ipp`) yields nothing noteworthy at all:
```
⬢[lorbus@toolbox examples]$ python debug.py 
/var/home/lorbus/code/python-ipp/examples/debug.py:50: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
```

And `ipps://192.168.1.73:631/ipp` yields an SSL error which doesn't seem unexpected to me as `ipps` is disabled:
```
⬢[lorbus@toolbox examples]$ python debug.py 
/var/home/lorbus/code/python-ipp/examples/debug.py:50: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
Traceback (most recent call last):
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 1146, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 1179, in _create_connection_transport
    await waiter
  File "/usr/lib64/python3.12/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib64/python3.12/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/pyipp/ipp.py", line 114, in _request
    response = await self.session.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/aiohttp/connector.py", line 996, in _wrap_create_connection
    raise ClientConnectorSSLError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorSSLError: Cannot connect to host 192.168.1.73:631 ssl:False [[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/home/lorbus/code/python-ipp/examples/debug.py", line 51, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/var/home/lorbus/code/python-ipp/examples/debug.py", line 12, in main
    response = await ipp.raw(
               ^^^^^^^^^^^^^^
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/pyipp/ipp.py", line 208, in raw
    return await self._request(data=message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/lorbus/.local/lib/python3.12/site-packages/pyipp/ipp.py", line 128, in _request
    raise IPPConnectionError(
pyipp.exceptions.IPPConnectionError: Error occurred while communicating with IPP server.
```

I'm happy to run more tests against the printer and provide logs here.

Also, thank you @ctalkington for making this project and for taking the time to take a look at this issue.

**Comment by ctalkington** [comment]
OK so this likely means your device isn't IPP 2.0 compatible. can you try adding version to the call:

https://github.com/ctalkington/python-ipp/blob/7a3e98f050ca84c464d7d3a0888fd15ddebf3581/examples/debug.py#L15

```
"version": (1, 1),
```

**Comment by ctalkington** [comment]
I updated the repo examples to include version in the debug and execute ones.

You may also try examples/execute.py with (1, 1) or even (1, 0) the issue may be lack of info since (2, 0) had better definition of inks levels iirc. still if you get it picking up printer at all I'd love to get a dump from debug to see what could be extracted.

**Comment by LorbusChris** [comment]
Thank you!
I didn't notice last time that `debug.py` created a file with the output. There isn't a lot in it when trying with v2, but v1.1 does indeed yield more! I've manually formatted this to be able to paste it here, original output files are attached below
`v2.0`:
```
attributes-charset utf-8H
attributes-natural-language en-us
```
`v1.1`:
```
attributes-charset utf-8
attributes-natural-language en-us
printer-name OKI-C822-5E330E
printer-location
printer-info PCL,XPS,IBMPPR,EPSONFX;
printer-more-info
printer-make-and-model C822#
printer-state !
printer-up-time o
printer-uri-supported http://192.168.1.73/ipp http://192.168.1.73:631/ipp http://192.168.1.73/ipp/lp http://192.168.1.73:631/ipp/lp ipp://192.168.1.73/ipp ipp://192.168.1.73:631/ipp ipp://192.168.1.73/ipp/lp ipp://192.168.1.73:631/ipp/lp
```

[v1.1-printer-attributes.bin.txt](https://github.com/ctalkington/python-ipp/files/14655051/v1.1-printer-attributes.bin.txt)
[v2.0-printer-attributes.bin.txt](https://github.com/ctalkington/python-ipp/files/14655052/v2.0-printer-attributes.bin.txt)
