### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 5: invalid start byte

### ISSUE THREAD

**Issue by dstrigl** [ctalkington/python-ipp#8]
I am using your `pyipp` package v0.8.3 in home-assistant (current dev branch) and get the following exception during startup:
```
Traceback (most recent call last):
  File "/home/pi/venv/homeassistant/lib/python3.7/site-packages/pyipp/ipp.py", line 151, in _request
    parsed_content = parse_response(content)
  File "/home/pi/venv/homeassistant/lib/python3.7/site-packages/pyipp/parser.py", line 158, in parse
    attribute, new_offset = parse_attribute(raw_data, offset)
  File "/home/pi/venv/homeassistant/lib/python3.7/site-packages/pyipp/parser.py", line 90, in parse_attribute
    attribute["value"] = data[offset:offset_length].decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 5: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/prog/homeassistant/core/homeassistant/data_entry_flow.py", line 109, in async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/home/pi/prog/homeassistant/core/homeassistant/data_entry_flow.py", line 172, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/home/pi/prog/homeassistant/core/homeassistant/components/ipp/config_flow.py", line 100, in async_step_zeroconf
    info = await validate_input(self.hass, self.discovery_info)
  File "/home/pi/prog/homeassistant/core/homeassistant/components/ipp/config_flow.py", line 40, in validate_input
    printer = await ipp.printer()
  File "/home/pi/venv/homeassistant/lib/python3.7/site-packages/pyipp/ipp.py", line 205, in printer
    "requested-attributes": DEFAULT_PRINTER_ATTRIBUTES,
  File "/home/pi/venv/homeassistant/lib/python3.7/site-packages/pyipp/ipp.py", line 192, in execute
    return await self._request(data=message)
  File "/home/pi/venv/homeassistant/lib/python3.7/site-packages/pyipp/ipp.py", line 153, in _request
    raise IPPParseError from exception
pyipp.exceptions.IPPParseError
```

I also tried it without home-assistant, just using your simple python example presented in the README.
Just the same exception!

My printer is a **Brother MFC-J5320DW**:
```
Firmware-Version
FIRM
    J1812012321 
```

Is there any information you additionally need, so that I can help you improve the package?

Regards,
Daniel.

**Comment by ctalkington** [comment]
hi, it would help to get the raw data. Im still working out the best approach for easily gathering that.

**Comment by ctalkington** [comment]
@dstrigl could you try the debug example with v0.9.0 and send the binary file. can email directly to my profile email if desired

**Comment by dstrigl** [comment]
Hi @ctalkington,

>@dstrigl could you try the debug example with v0.9.0 and send the binary file
> "printer-attributes.bin" can email directly to my profile email if desired

I tried it, but got the following exception:

```
(ipp) pi@homeassistant:~/prog/python-ipp/examples $ python debug.py
Traceback (most recent call last):
  File "debug.py", line 39, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "debug.py", line 26, in main
    "printer-is-shared",
  File "/home/pi/prog/python-ipp/pyipp/ipp.py", line 198, in raw
    return await self._request(data=message)
  File "/home/pi/prog/python-ipp/pyipp/ipp.py", line 107, in _request
    data = encode_dict(data)
  File "/home/pi/prog/python-ipp/pyipp/serializer.py", line 69, in encode_dict
    encoded += struct.pack(">h", operation.value)
AttributeError: 'int' object has no attribute 'value'
```
So, no `printer-attributes.bin` file was written :-(

Regards,
Daniel.

**Comment by ctalkington** [comment]
ah seems trying to simplify the example led to having wrong datatype. Can you try with latest commit?

**Comment by dstrigl** [comment]
@ctalkington now it worked :-)

See the file `printer-attributes.bin` in the attachment ...

[printer-attributes.bin.zip](https://github.com/ctalkington/python-ipp/files/4445962/printer-attributes.bin.zip)

**Comment by ctalkington** [comment]
@dstrigl thank you. It appears that the issue is that of languages when the printer base language isnt English it has to use a different value for text fields. That defines the language of the text as "for example. Im looking into a solution

**Comment by dstrigl** [comment]
:+1:

**Comment by ctalkington** [comment]
@dstrigl 0.9.1 should resolve the language issue by picking up more of the ipp spec.

It should likely be part of HA 0.108.1 since it missed the window for 0.108.0

**Comment by dstrigl** [comment]
Great 👍, nowit works fine!
